/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pMain;

/**
 *
 * @author lvhung
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbNavigator = new javax.swing.JToolBar();
        bntFirst = new javax.swing.JButton();
        bntPrior = new javax.swing.JButton();
        bntNext = new javax.swing.JButton();
        bntLast = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbNavigator.setRollover(true);

        bntFirst.setText("First");
        bntFirst.setFocusable(false);
        bntFirst.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bntFirst.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbNavigator.add(bntFirst);

        bntPrior.setText("Prior");
        bntPrior.setFocusable(false);
        bntPrior.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bntPrior.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbNavigator.add(bntPrior);

        bntNext.setText("Next");
        bntNext.setFocusable(false);
        bntNext.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bntNext.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbNavigator.add(bntNext);

        bntLast.setText("Last");
        bntLast.setFocusable(false);
        bntLast.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bntLast.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbNavigator.add(bntLast);

        getContentPane().add(tbNavigator, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 966, 25));
        tbNavigator.getAccessibleContext().setAccessibleName("");

        jMenuBar1.setToolTipText("");
        jMenuBar1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jMenuBar1.setSelectionModel(null);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntFirst;
    private javax.swing.JButton bntLast;
    private javax.swing.JButton bntNext;
    private javax.swing.JButton bntPrior;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToolBar tbNavigator;
    // End of variables declaration//GEN-END:variables
}
